apiVersion: v1
kind: Service
metadata:
  name: {{ include "default-http-backend.fullname" . }}
  labels:
    {{- include "default-http-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.httpPort.name }}
      port: {{ .Values.service.httpPort.port }}
      targetPort: {{ .Values.service.httpPort.targetPort }}
      protocol: {{ .Values.service.httpPort.protocol }}
    {{- if .Values.service.extraPorts }}
    {{- range $index, $port := .Values.service.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "default-http-backend.selectorLabels" . | nindent 4 }}